/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import edu.princeton.cs.algs4.Draw;

public class App {

    private Draw draw;

    public App() {

        this.draw = new Draw();
        this.draw.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.draw.setCanvasSize(1000,600);
        this.draw.setXscale(0,1000);
        this.draw.setYscale(0,600);

        Grade g = new Grade();

        g.desenhar(this.draw);
        g.desenhar(this.draw);

    }

    public static void main(String[] args) {

        App app = new App();
        app.draw.show();

    }

}
